baseURL = "http://news.xmr.ru"
languageCode = "ru"
title = "Monero News"
theme = "xmag"
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
paginate = 6
publishDir = "public"
rssLimit = 20
enableRobotsTXT  = true

[author]
    name = "Monerorus and XMR.RU team"
    
[params.text]
    back = "&larr; На главную"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
    uncategorized = "без категории"
    
[[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Категории"
    url = "/categories/"
    weight = 3
    
[params]
    description = "Новости из мира Monero"
    summary_length = 300
    footer = "&copy; MoneroRus 2019 | [Github](https://github.com/monerorus/xmr_news) | [XMR.RU](https://xmr.ru)"
    
[imaging]
quality = 100
anchor = "smart"